spring:
  application:
    name: producer-app
  kafka:
    properties:
      sasl:
        jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="alice" password="alice-secret";
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
  cloud:
    stream:
      source: myoutput
      bindings:
        default:
          producer:
            headerMode: headers
        myoutput-out-0:
          destination: mytopic
          group: ${spring.application.name}
      kafka:
        binder:
          brokers: localhost:9092
